Adapt dekorate
snowdrop/spring-boot-health-check-booster pull request #82
Opened 2022-08-02 11:02 UTC by jacobdotcosta

2022-09-02 05:28 UTC, Sgitario requested changes
Same comments as in other reviews.

2022-09-08 11:53 UTC, Sgitario requested changes
Also, missing <version>${spring-boot.version}</version>`  in the spring maven plugin.

2022-09-08 11:53 UTC, Sgitario commented on README.md
> +./run_tests_with_dekorate.sh -v "2.6.7"
The script needs to be updated to follow the same convention as done in the rest-http example, right?

2022-09-08 15:12 UTC, jacobdotcosta commented on README.md
> +./run_tests_with_dekorate.sh -v "2.6.7"
done.

2022-09-09 05:10 UTC, Sgitario approved these changes
lgtm now, conflicts need to be resolved before merging

2022-09-12 06:45 UTC, merged